# Generated by Django 5.2 on 2025-05-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product_detail'),
            preserve_default=False,
        ),
    ]
