# Generated by Django 5.2 on 2025-05-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_created_cart_added_at_cart_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedItem',
        ),
    ]
