# Generated by Django 5.2 on 2025-05-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
