# Generated by Django 5.2 on 2025-05-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('availability_text', models.CharField(default='In Stock', max_length=100)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_time', models.CharField(default='02 day shipping', max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_tips', models.TextField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient_type', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('package_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('net_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=200, null=True)),
                ('asin', models.CharField(blank=True, max_length=100, null=True)),
                ('best_sellers_rank', models.CharField(blank=True, max_length=200, null=True)),
                ('date_first_available', models.DateField(blank=True, null=True)),
                ('item_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='core.category')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
