# Generated by Django 5.2 on 2025-05-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(default='Not Provided', max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(blank=True, default='Not Provided', max_length=80, null=True)),
                ('password', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='defaultprofilepic.jpg', upload_to='profile_images/')),
                ('password_reset_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('is_permanently_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_info', to='accounts.user')),
            ],
        ),
    ]
